### PR TITLE
Chapter 05  alternate setup for libs

### PR DESCRIPTION
**Pull request by ImJohnMDaniel**
Changes made:
* moved all metadata files into Salesforce Falcon Template approach to support multiple PackageDirectories
* moved classes related to Apex Mocks to `sfdx-source/fflib-apex-mocks`
* moved classes related to Apex Common to `sfdx-source/fflib-apex-common`
* moved classes related to FormulaForce to `sfdx-source/formulaforce`
* moved test classes related to FormulaForce to `sfdx-source/formulaforce/test/classes`

### CODE REVIEW

**Comment by ImJohnMDaniel** [comment]
@afawcett -- FYI on this PR

**Comment by afawcett** [comment]
Is this correct re: `force-app`? I think no? 

    {
      "packageDirectories": [
        {
          "path": "sfdx-source/fflib-apex-mocks",
          "default": false
        },
        {
          "path": "sfdx-source/fflib-apex-common",
          "default": false
        },
        {
          "path": "force-app",
          "default": true
        }
      ],
      "namespace": "",
      "sfdcLoginUrl": "https://login.salesforce.com",
      "sourceApiVersion": "55.0"
    }

**Comment by afawcett** [comment]
Also `/sfdx-source/fomrulaforce/main/default` i thought you didn't like `default` or no?

**Comment by afawcett** [comment]
I am also pondering over using `sfdx-source` (vs `source`) since in the final chapters the books add `/node-app` and `/node-service` (Heroku apps) are introduced into the repo - and also '`sfdx`' seems somewhat redudent. Thinking about `/source/formulaforce`, `/source/fflib-apex-commons`, `/source/fflib-apex-mocks` and then `/source/node-app` and `/source/node-service` thoughts?

**Comment by afawcett** [comment]
Also special favor - no worries if not - once we are aligned here - can you do a PR for chapter 6 and 7 branches?

**Comment by ImJohnMDaniel** [comment]
@afawcett 

re: `sfdx-project.json`
> Is this correct re: `force-app`? I think no?
Fixed

re: "default" directory and my dislike for it 
Fixed ;-) 

re: usage of `sfdx-source` verses `source`
The reference to `sfdx-source` originates from Vivek Chawla's introduction of the "Falcon Template" project directory layout pattern.  At the time, it provided a distinction between DX Source Formatted metadata and the legacy Metadata Formatted directory structure.  It is the de facto standard for projects that I am running.  Having said that, there is nothing stopping you from using just `source`.   In short.... author's discretion.  ;-) 

re: once aligned - open PRs
Absolutely.

**Comment by afawcett** [comment]
Thanks @ImJohnMDaniel - lets go with `/source` then - we are now aligned. Thanks!

**Comment by afawcett** [comment]
btw, we are sticking with api 55 for the book unless you thnk thats an issue?

**Comment by ImJohnMDaniel** [comment]
I would recommend updating to 56 at minimum.

**Pull request closed without merging**
